Deleted extra cruft from the masterfiles build
cfengine/cfbs-index pull request #7
Opened 2021-10-01 20:13 UTC by nickanderson

2021-10-01 20:28 UTC, nickanderson commented
@olehermanse what do you think, should we cull the other extra bits, Changelog, code of conduct, contributing, license, mpf.md, readme.md ?

2021-10-01 20:42 UTC, nickanderson commented
@olehermanse  I went ahead and added another commit to cleanup the other bits, just lmk what you think we should keep from that or not.

2021-10-01 20:47 UTC, craigcomstock commented on index.json
> +      "steps": [
do you also need to get rid of `.git` or any other hidden files/dirs at that top level? Like `.travis.yml`, `.CFVERSION`, `.gitignore`, `.mailmap` maybe?

2021-10-04 15:29 UTC, olehermanse requested changes

2021-10-04 15:29 UTC, olehermanse commented on index.json
> +          "delete ./controls/update_def.cf.in",
As indicated in slack, I think this list should be in the masterfiles repo, not in the index / cfbs json. We can put a `cleanup.sh` script in masterfiles:

```suggestion
          "run cleanup.sh",
          "delete cleanup.sh",
```

2021-10-04 17:02 UTC, nickanderson commented
@olehermanse as you wish.

2021-10-04 17:10 UTC, merged